### ISSUE TITLE
I met this error when run ShapeMatching.py

### ISSUE THREAD

**Issue by bemoregt** [zcsd/ShapeMatching#1]
Hi, @zcsd 

I met this error when run ShapeMatching.py

MacPro:ShapeMatching irix$ python3 ShapeMatching.py 
Shape Matching Using Fourier Descriptor
Traceback (most recent call last):
  File "ShapeMatching.py", line 175, in <module>
    getTempleteCV()
  File "ShapeMatching.py", line 57, in getTempleteCV
    tpContour = getContours(templeteROI)
  File "ShapeMatching.py", line 48, in getContours
    imgcontours, contours, hierarchy = cv2.findContours(imgdilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)
MacPro:ShapeMatching irix$ 

What's wrong to me ?

My Env:
python 3.8.3
At OSX Catalina Terminal

Thanks.
Best,

@bemoregt.

**Comment by Phreak87** [comment]
you can fix by changing 
"imgcontours, contours, hierarchy = cv2.findContours(imgdilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)" 
to
"contours, hierarchy = cv2.findContours(imgdilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)"
